#!/usr/bin/with-contenv bash

if [ ! -f /config/aria2.conf ]; then
    echo "*** using template aria2.conf"
    cp /defaults/aria2.conf /config/aria2.conf
else
    echo "*** using existing aria2.conf"
fi

chown -R abc:abc \
    /config \
    /download

# version info
echo "*** aria2 v$(echo $(aria2c -v) | awk '{print $3}') ready!"
