#!/usr/bin/with-contenv bash

IFS=" " read -r -a RUN_ARGS <<< "$USER_OPTS"

mount_command="aria2c --conf-path=/config/aria2.conf --disable-ipv6=true --enable-rpc --rpc-listen-all --rpc-allow-origin-all --rpc-listen-port=6800 -d /download"
mount_command="$mount_command${RPC_SECRET:+ --rpc-secret=$RPC_SECRET} ${RUN_ARGS[@]}"

echo "running => $mount_command"
exec \
	s6-setuidgid abc $mount_command
